Create database DS;
use DS;

CREATE TABLE cantor (
    cd_cantor INT PRIMARY KEY AUTO_INCREMENT,
    nm_cantor VARCHAR(100) NOT NULL,
    dt_formacao YEAR
);

CREATE TABLE album (
    cd_album INT PRIMARY KEY AUTO_INCREMENT,
    nm_album VARCHAR(100) NOT NULL,
    dt_lancamento YEAR,
    fk_cd_cantor INT,
    FOREIGN KEY (fk_cd_cantor) REFERENCES cantor (cd_cantor)
);

CREATE TABLE musica (
    cd_musica INT PRIMARY KEY AUTO_INCREMENT,
    nm_musica VARCHAR(100) NOT NULL,
    fk_cd_album INT,
    FOREIGN KEY (fk_cd_album) REFERENCES album (cd_album)
);

INSERT INTO cantor VALUES
(null, 'Creedence Clearwater Revival', 1967),
(null, 'Queen', 1970),
(null, 'Skid Row', 1986),
(null, 'Bon Jovi', 1983),
(null, 'Elvis Presley', 1954),
(null, 'Chuck Berry', 1955),
(null, 'Raul Seixas', 1968),
(null, 'ABBA', 1972),
(null, 'Black Sabbath', 1968),
(null, 'Guns N'' Roses', 1985),
(null, 'Bob Seger', 1961),
(null, 'Metallica', 1981),
(null, 'Pink Floyd', 1965),
(null, 'The Manhattans', 1962),
(null, 'Slipknot', 1995);

INSERT INTO album  VALUES
-- Creedence Clearwater Revival 
(null, 'Bayou Country', 1969, 1),
(null, 'Green River', 1969, 1),
(null, 'Cosmo''s Factory', 1970, 1),

-- Queen 
(null, 'A Night at the Opera', 1975, 2),
(null, 'News of the World', 1977, 2),
(null, 'The Game', 1980, 2),

-- Skid Row 
(null, 'Skid Row', 1989, 3),
(null, 'Slave to the Grind', 1991, 3),
(null, 'Subhuman Race', 1995, 3),

-- Bon Jovi 
(null, 'Slippery When Wet', 1986, 4),
(null, 'New Jersey', 1988, 4),
(null, 'Keep the Faith', 1992, 4),

-- Elvis Presley 
(null, 'Elvis Presley', 1956, 5),
(null, 'Elvis', 1956, 5),
(null, 'Elvis'' Christmas Album', 1957, 5),

-- Chuck Berry 
(null, 'After School Session', 1957, 6),
(null, 'One Dozen Berrys', 1958, 6),
(null, 'Chuck Berry Is on Top', 1959, 6),

-- Raul Seixas 
(null, 'Krig-ha, Bandolo!', 1973, 7),
(null, 'Gita', 1974, 7),
(null, 'Novo Aeon', 1975, 7),

-- ABBA 
(null, 'Waterloo', 1974, 8),
(null, 'ABBA', 1975, 8),
(null, 'Arrival', 1976, 8),

-- Black Sabbath 
(null, 'Black Sabbath', 1970, 9),
(null, 'Paranoid', 1970, 9),
(null, 'Master of Reality', 1971, 9),

-- Guns N' Roses 
(null, 'Appetite for Destruction', 1987, 10),
(null, 'Use Your Illusion I', 1991, 10),
(null, 'Use Your Illusion II', 1991, 10),

-- Bob Seger 
(null, 'Night Moves', 1976, 11),
(null, 'Stranger in Town', 1978, 11),
(null, 'Against the Wind', 1980, 11),

-- Metallica 
(null, 'Master of Puppets', 1986, 12),
(null, 'And Justice for All', 1988, 12),
(null, 'Metallica (Black Album)', 1991, 12),

-- Pink Floyd 
(null, 'The Dark Side of the Moon', 1973, 13),
(null, 'Wish You Were Here', 1975, 13),
(null, 'The Wall', 1979, 13),

-- The Manhattans 
(null, 'There''s No Me Without You', 1973, 14),
(null, 'That''s How Much I Love You', 1974, 14),
(null, 'The Manhattans', 1975, 14),

-- Slipknot 
(null, 'Slipknot', 1999, 15),
(null, 'Iowa', 2001, 15),
(null, 'Vol. 3: (The Subliminal Verses)', 2004, 15);

INSERT INTO album  VALUES

(null, 'Bayou Country', 1969, 1),
(null, 'Green River', 1969, 1),
(null, 'Cosmo''s Factory', 1970, 1),


(null, 'A Night at the Opera', 1975, 2),
(null, 'News of the World', 1977, 2),
(null, 'The Game', 1980, 2),


(null, 'Skid Row', 1989, 3),
(null, 'Slave to the Grind', 1991, 3),
(null, 'Subhuman Race', 1995, 3),


(null, 'Slippery When Wet', 1986, 4),
(null, 'New Jersey', 1988, 4),
(null, 'Keep the Faith', 1992, 4),


(null, 'Elvis Presley', 1956, 5),
(null, 'Elvis', 1956, 5),
(null, 'Elvis'' Christmas Album', 1957, 5),


(null, 'After School Session', 1957, 6),
(null, 'One Dozen Berrys', 1958, 6),
(null, 'Chuck Berry Is on Top', 1959, 6),

(null, 'Krig-ha, Bandolo!', 1973, 7),
(null, 'Gita', 1974, 7),
(null, 'Novo Aeon', 1975, 7),


(null, 'Waterloo', 1974, 8),
(null, 'ABBA', 1975, 8),
(null, 'Arrival', 1976, 8),


(null, 'Black Sabbath', 1970, 9),
(null, 'Paranoid', 1970, 9),
(null, 'Master of Reality', 1971, 9),


(null, 'Appetite for Destruction', 1987, 10),
(null, 'Use Your Illusion I', 1991, 10),
(null, 'Use Your Illusion II', 1991, 10),


(null, 'Night Moves', 1976, 11),
(null, 'Stranger in Town', 1978, 11),
(null, 'Against the Wind', 1980, 11),


(null, 'Master of Puppets', 1986, 12),
(null, 'And Justice for All', 1988, 12),
(null, 'Metallica (Black Album)', 1991, 12),


(null, 'The Dark Side of the Moon', 1973, 13),
(null, 'Wish You Were Here', 1975, 13),
(null, 'The Wall', 1979, 13),


(null, 'There''s No Me Without You', 1973, 14),
(null, 'That''s How Much I Love You', 1974, 14),
(null, 'The Manhattans', 1975, 14),


(null, 'Slipknot', 1999, 15),
(null, 'Iowa', 2001, 15),
(null, 'Vol. 3: (The Subliminal Verses)', 2004, 15);


INSERT INTO musica  VALUES

(null, 'Born on the Bayou', 1),
(null, 'Bootleg', 1),
(null, 'Graveyard Train', 1),
(null, 'Good Golly Miss Molly', 1),
(null, 'Penthouse Pauper', 1),
(null, 'Proud Mary', 1),
(null, 'Keep on Chooglin''', 1),
(null, 'Bayou Song', 1),
(null, 'Swamp Water', 1),
(null, 'Louisiana Blues', 1),
(null, 'River Road', 1),
(null, 'Muddy Waters', 1),
(null, 'Country Boy', 1),
(null, 'Southern Comfort', 1),
(null, 'Delta Dawn', 1),


(null, 'Green River', 2),
(null, 'Commotion', 2),
(null, 'Tombstone Shadow', 2),
(null, 'Wrote a Song for Everyone', 2),
(null, 'Bad Moon Rising', 2),
(null, 'Lodi', 2),
(null, 'Cross-Tie Walker', 2),
(null, 'Sinister Purpose', 2),
(null, 'The Night Time Is the Right Time', 2),
(null, 'Riverside Blues', 2),
(null, 'Foggy Mountain', 2),
(null, 'Swamp Thing', 2),
(null, 'Green Light', 2),
(null, 'River Song', 2),
(null, 'Country Roads', 2),


(null, 'Ramble Tamble', 3),
(null, 'Before You Accuse Me', 3),
(null, 'Travelin'' Band', 3),
(null, 'Ooby Dooby', 3),
(null, 'Lookin'' Out My Back Door', 3),
(null, 'Run Through the Jungle', 3),
(null, 'Up Around the Bend', 3),
(null, 'My Baby Left Me', 3),
(null, 'Who''ll Stop the Rain', 3),
(null, 'I Heard It Through the Grapevine', 3),
(null, 'Long As I Can See the Light', 3),
(null, 'Factory Blues', 3),
(null, 'Cosmic Journey', 3),
(null, 'Space Traveler', 3),
(null, 'Universal Sound', 3),


(null, 'Death on Two Legs', 4),
(null, 'Lazing on a Sunday Afternoon', 4),
(null, 'I''m in Love with My Car', 4),
(null, 'You''re My Best Friend', 4),
(null, '''39', 4),
(null, 'Sweet Lady', 4),
(null, 'Seaside Rendezvous', 4),
(null, 'The Prophet''s Song', 4),
(null, 'Love of My Life', 4),
(null, 'Good Company', 4),
(null, 'Bohemian Rhapsody', 4),
(null, 'God Save the Queen', 4),
(null, 'Opera House', 4),
(null, 'Royal Performance', 4),
(null, 'Theater Night', 4),


(null, 'We Will Rock You', 5),
(null, 'We Are the Champions', 5),
(null, 'Sheer Heart Attack', 5),
(null, 'All Dead, All Dead', 5),
(null, 'Spread Your Wings', 5),
(null, 'Fight from the Inside', 5),
(null, 'Get Down, Make Love', 5),
(null, 'Sleeping on the Sidewalk', 5),
(null, 'Who Needs You', 5),
(null, 'It''s Late', 5),
(null, 'My Melancholy Blues', 5),
(null, 'World News', 5),
(null, 'Breaking News', 5),
(null, 'Headlines', 5),
(null, 'Press Release', 5),


(null, 'Play the Game', 6),
(null, 'Dragon Attack', 6),
(null, 'Another One Bites the Dust', 6),
(null, 'Need Your Loving Tonight', 6),
(null, 'Crazy Little Thing Called Love', 6),
(null, 'Rock It (Prime Jive)', 6),
(null, 'Don''t Try Suicide', 6),
(null, 'Sail Away Sweet Sister', 6),
(null, 'Coming Soon', 6),
(null, 'Save Me', 6),
(null, 'Game Over', 6),
(null, 'Victory Song', 6),
(null, 'Championship', 6),
(null, 'Final Round', 6),
(null, 'Winner Takes All', 6),


(null, 'Big Guns', 7),
(null, 'Sweet Little Sister', 7),
(null, 'Can''t Stand the Heartache', 7),
(null, 'Piece of Me', 7),
(null, '18 and Life', 7),
(null, 'Rattlesnake Shake', 7),
(null, 'Youth Gone Wild', 7),
(null, 'Here I Am', 7),
(null, 'Makin'' a Mess', 7),
(null, 'I Remember You', 7),
(null, 'Midnight/Tornado', 7),
(null, 'Street Fighter', 7),
(null, 'Bad Attitude', 7),
(null, 'Rebel Yell', 7),
(null, 'Wild Side', 7),


(null, 'Monkey Business', 8),
(null, 'Slave to the Grind', 8),
(null, 'The Threat', 8),
(null, 'Quicksand Jesus', 8),
(null, 'Psycho Love', 8),
(null, 'Get the Fuck Out', 8),
(null, 'Livin'' on a Chain Gang', 8),
(null, 'Creepshow', 8),
(null, 'In a Darkened Room', 8),
(null, 'Riot Act', 8),
(null, 'Mudkicker', 8),
(null, 'Wasted Time', 8),
(null, 'Grinding Stone', 8),
(null, 'Chain Reaction', 8),
(null, 'Breaking Free', 8),


(null, 'My Enemy', 9),
(null, 'Firesign', 9),
(null, 'Bonehead', 9),
(null, 'Beat Yourself Blind', 9),
(null, 'Eileen', 9),
(null, 'Remains to Be Seen', 9),
(null, 'Subhuman Race', 9),
(null, 'Frozen', 9),
(null, 'Into Another', 9),
(null, 'Face Against My Soul', 9),
(null, 'Medicine Jar', 9),
(null, 'Breakin'' Down', 9),
(null, 'Iron Will', 9),
(null, 'Psycho Therapy', 9),
(null, 'Mudkicker', 9),


(null, 'Let It Rock', 10),
(null, 'You Give Love a Bad Name', 10),
(null, 'Livin'' on a Prayer', 10),
(null, 'Social Disease', 10),
(null, 'Wanted Dead or Alive', 10),
(null, 'Raise Your Hands', 10),
(null, 'Without Love', 10),
(null, 'I''d Die for You', 10),
(null, 'Never Say Goodbye', 10),
(null, 'Wild in the Streets', 10),
(null, 'Slippery Road', 10),
(null, 'Wet Dreams', 10),
(null, 'Rock Anthem', 10),
(null, 'Stadium Song', 10),
(null, 'Arena Rock', 10),


(null, 'Lay Your Hands on Me', 11),
(null, 'Bad Medicine', 11),
(null, 'Born to Be My Baby', 11),
(null, 'Living in Sin', 11),
(null, 'Blood on Blood', 11),
(null, 'Homebound Train', 11),
(null, 'Wild Is the Wind', 11),
(null, 'Ride Cowboy Ride', 11),
(null, 'Stick to Your Guns', 11),
(null, 'I''ll Be There for You', 11),
(null, '99 in the Shade', 11),
(null, 'Love for Sale', 11),
(null, 'Jersey Girl', 11),
(null, 'Garden State', 11),
(null, 'East Coast', 11),


(null, 'I Believe', 12),
(null, 'Keep the Faith', 12),
(null, 'I''ll Sleep When I''m Dead', 12),
(null, 'In These Arms', 12),
(null, 'Bed of Roses', 12),
(null, 'If I Was Your Mother', 12),
(null, 'Dry County', 12),
(null, 'Woman in Love', 12),
(null, 'Fear', 12),
(null, 'I Want You', 12),
(null, 'Blame It on the Love of Rock & Roll', 12),
(null, 'Little Bit of Soul', 12),
(null, 'Save a Prayer', 12),
(null, 'Faith Keeper', 12),
(null, 'Believer', 12),


(null, 'Blue Suede Shoes', 13),
(null, 'I''m Counting on You', 13),
(null, 'I Got a Woman', 13),
(null, 'One-Sided Love Affair', 13),
(null, 'I Love You Because', 13),
(null, 'Just Because', 13),
(null, 'Tutti Frutti', 13),
(null, 'Trying to Get to You', 13),
(null, 'I''m Gonna Sit Right Down and Cry', 13),
(null, 'I''ll Never Let You Go', 13),
(null, 'Blue Moon', 13),
(null, 'Money Honey', 13),
(null, 'Shake, Rattle and Roll', 13),
(null, 'Lawdy Miss Clawdy', 13),
(null, 'Mystery Train', 13),


(null, 'Rip It Up', 14),
(null, 'Love Me', 14),
(null, 'When My Blue Moon Turns to Gold Again', 14),
(null, 'Long Tall Sally', 14),
(null, 'First in Line', 14),
(null, 'Paralyzed', 14),
(null, 'So Glad You''re Mine', 14),
(null, 'Old Shep', 14),
(null, 'Ready Teddy', 14),
(null, 'Anyplace Is Paradise', 14),
(null, 'How''s the World Treating You', 14),
(null, 'How Do You Think I Feel', 14),
(null, 'King Creole', 14),
(null, 'Hound Dog', 14),
(null, 'Don''t Be Cruel', 14),


(null, 'Santa Claus Is Back in Town', 15),
(null, 'White Christmas', 15),
(null, 'Here Comes Santa Claus', 15),
(null, 'I''ll Be Home for Christmas', 15),
(null, 'Blue Christmas', 15),
(null, 'Santa Bring My Baby Back', 15),
(null, 'O Little Town of Bethlehem', 15),
(null, 'Silent Night', 15),
(null, 'Peace in the Valley', 15),
(null, 'I Believe', 15),
(null, 'Take My Hand, Precious Lord', 15),
(null, 'It Is No Secret', 15),
(null, 'Christmas Song', 15),
(null, 'Holiday Blues', 15),
(null, 'Jingle Bell Rock', 15),


(null, 'School Days', 16),
(null, 'Deep Feeling', 16),
(null, 'Too Much Monkey Business', 16),
(null, 'Wee Wee Hours', 16),
(null, 'No Money Down', 16),
(null, 'Downbound Train', 16),
(null, 'Havana Moon', 16),
(null, 'Drifting Heart', 16),
(null, 'La Jaunda', 16),
(null, 'Together', 16),
(null, 'Thirty Days', 16),
(null, 'You Can''t Catch Me', 16),
(null, 'Roll Over Beethoven', 16),
(null, 'Berry Picking', 16),
(null, 'Guitar Boogie', 16),


(null, 'Sweet Little Sixteen', 17),
(null, 'Blue Feeling', 17),
(null, 'La Jaunda', 17),
(null, 'Rockin'' at the Hops', 17),
(null, 'Oh Baby Doll', 17),
(null, 'Reelin'' and Rockin''', 17),
(null, 'In-Go', 17),
(null, 'Rock and Roll Music', 17),
(null, 'How You''ve Changed', 17),
(null, 'Low Feeling', 17),
(null, 'It Don''t Take but a Few Minutes', 17),
(null, 'Around and Around', 17),
(null, 'Johnny B. Goode', 17),
(null, 'Duck Walk', 17),
(null, 'Berry''s Boogie', 17),


(null, 'Almost Grown', 18),
(null, 'Carol', 18),
(null, 'Maybellene', 18),
(null, 'Sweet Little Rock and Roller', 18),
(null, 'Anthony Boy', 18),
(null, 'Johnny B. Goode', 18),
(null, 'Little Queenie', 18),
(null, 'Jo Jo Gunne', 18),
(null, 'Roll Over Beethoven', 18),
(null, 'Around and Around', 18),
(null, 'Hey Pedro', 18),
(null, 'Blues for Hawaiians', 18),
(null, 'Top Performer', 18),
(null, 'Chart Topper', 18),
(null, 'Number One', 18),


(null, 'Ouro de Tolo', 19),
(null, 'Al Capone', 19),
(null, 'Mosca na Sopa', 19),
(null, 'Metamorfose Ambulante', 19),
(null, 'Sociedade Alternativa', 19),
(null, 'Dentadura Postiça', 19),
(null, 'Cachorro Urubu', 19),
(null, 'Raulzito', 19),
(null, 'Krig-ha, Bandolo!', 19),
(null, 'Loteria da Babilônia', 19),
(null, 'Eu Nasci Há Dez Mil Anos Atrás', 19),
(null, 'Maluco Beleza', 19),
(null, 'Rock do Diabo', 19),
(null, 'Gita', 19),
(null, 'Tente Outra Vez', 19),


(null, 'Prelúdio', 20),
(null, 'Gita', 20),
(null, 'S.O.S.', 20),
(null, 'Eu Sou Egoísta', 20),
(null, 'Ambulante', 20),
(null, 'Tente Outra Vez', 20),
(null, 'Tu És o MDC da Minha Vida', 20),
(null, 'A Verdade Sobre a Nostalgia', 20),
(null, 'Caminhos', 20),
(null, 'Como Vovô Já Dizia', 20),
(null, 'Que Luz É Essa?', 20),
(null, 'Sunseed', 20),
(null, 'Bhagavad Gita', 20),
(null, 'Filosofia Hindu', 20),
(null, 'Sabedoria Oriental', 20),


(null, 'Novo Aeon', 21),
(null, 'A Maçã', 21),
(null, 'Trem das 7', 21),
(null, 'Fool''s Gold', 21),
(null, 'Eu Também Vou Reclamar', 21),
(null, 'Maluco Beleza', 21),
(null, 'Medo da Chuva', 21),
(null, 'Rockixe', 21),
(null, 'Sunseed', 21),
(null, 'A Pedra do Gênesis', 21),
(null, 'Novo Tempo', 21),
(null, 'Era de Aquário', 21),
(null, 'Despertar', 21),
(null, 'Consciência', 21),
(null, 'Evolução', 21),


(null, 'Waterloo', 22),
(null, 'Sitting in the Palmtree', 22),
(null, 'King Kong Song', 22),
(null, 'Hasta Mañana', 22),
(null, 'My Mama Said', 22),
(null, 'Dance (While the Music Still Goes On)', 22),
(null, 'Honey, Honey', 22),
(null, 'Watch Out', 22),
(null, 'What About Livingstone', 22),
(null, 'Gonna Sing You My Lovesong', 22),
(null, 'Suzy-Hang-Around', 22),
(null, 'Waterloo (French Version)', 22),
(null, 'Swedish Pop', 22),
(null, 'Eurovision Song', 22),
(null, 'Victory Dance', 22),


(null, 'Mamma Mia', 23),
(null, 'Hey, Hey Helen', 23),
(null, 'Tropical Loveland', 23),
(null, 'SOS', 23),
(null, 'Man in the Middle', 23),
(null, 'Bang-A-Boomerang', 23),
(null, 'I Do, I Do, I Do, I Do, I Do', 23),
(null, 'Rock Me', 23),
(null, 'Intermezzo No. 1', 23),
(null, 'I''ve Been Waiting for You', 23),
(null, 'So Long', 23),
(null, 'Swedish Sensation', 23),
(null, 'Pop Perfection', 23),
(null, 'Disco Queen', 23),
(null, 'Dance Floor', 23),


(null, 'When I Kissed the Teacher', 24),
(null, 'Dancing Queen', 24),
(null, 'My Love, My Life', 24),
(null, 'Dum Dum Diddle', 24),
(null, 'Knowing Me, Knowing You', 24),
(null, 'Money, Money, Money', 24),
(null, 'That''s Me', 24),
(null, 'Why Did It Have to Be Me', 24),
(null, 'Tiger', 24),
(null, 'Arrival', 24),
(null, 'Fernando', 24),
(null, 'Happy New Year', 24),
(null, 'Swedish Gold', 24),
(null, 'Pop Royalty', 24),
(null, 'Disco Fever', 24),


(null, 'Black Sabbath', 25),
(null, 'The Wizard', 25),
(null, 'Behind the Wall of Sleep', 25),
(null, 'N.I.B.', 25),
(null, 'Evil Woman', 25),
(null, 'Sleeping Village', 25),
(null, 'Warning', 25),
(null, 'Wicked World', 25),
(null, 'A Bit of Finger', 25),
(null, 'Wasp', 25),
(null, 'Bassically', 25),
(null, 'Sabbath Bloody Sabbath', 25),
(null, 'Heavy Metal', 25),
(null, 'Dark Lord', 25),
(null, 'Doom Metal', 25),


(null, 'War Pigs', 26),
(null, 'Paranoid', 26),
(null, 'Planet Caravan', 26),
(null, 'Iron Man', 26),
(null, 'Electric Funeral', 26),
(null, 'Hand of Doom', 26),
(null, 'Rat Salad', 26),
(null, 'Fairies Wear Boots', 26),
(null, 'Luke''s Wall', 26),
(null, 'Jack the Stripper', 26),
(null, 'Paranoia', 26),
(null, 'Mental Health', 26),
(null, 'Anxiety', 26),
(null, 'Fear Factor', 26),
(null, 'Panic Attack', 26),


(null, 'Sweet Leaf', 27),
(null, 'After Forever', 27),
(null, 'Embryo', 27),
(null, 'Children of the Grave', 27),
(null, 'Orchid', 27),
(null, 'Lord of This World', 27),
(null, 'Solitude', 27),
(null, 'Into the Void', 27),
(null, 'Deathmask', 27),
(null, 'Every Day Comes and Goes', 27),
(null, 'Reality Check', 27),
(null, 'Master Plan', 27),
(null, 'Truth Seeker', 27),
(null, 'Reality Bites', 27),
(null, 'Master Class', 27),


(null, 'Welcome to the Jungle', 28),
(null, 'It''s So Easy', 28),
(null, 'Nightrain', 28),
(null, 'Out ta Get Me', 28),
(null, 'Mr. Brownstone', 28),
(null, 'Paradise City', 28),
(null, 'My Michelle', 28),
(null, 'Think About You', 28),
(null, 'Sweet Child O'' Mine', 28),
(null, 'You''re Crazy', 28),
(null, 'Anything Goes', 28),
(null, 'Rocket Queen', 28),
(null, 'Move to the City', 28),
(null, 'Mama Kin', 28),
(null, 'Nice Boys', 28),


(null, 'Right Next Door to Hell', 29),
(null, 'Dust N'' Bones', 29),
(null, 'Live and Let Die', 29),
(null, 'Don''t Cry', 29),
(null, 'Perfect Crime', 29),
(null, 'You Ain''t the First', 29),
(null, 'Bad Obsession', 29),
(null, 'Back off Bitch', 29),
(null, 'Double Talkin'' Jive', 29),
(null, 'November Rain', 29),
(null, 'The Garden', 29),
(null, 'Garden of Eden', 29),
(null, 'Don''t Damn Me', 29),
(null, 'Bad Apples', 29),
(null, 'Dead Horse', 29),


(null, 'Civil War', 30),
(null, '14 Years', 30),
(null, 'Yesterdays', 30),
(null, 'Knockin'' on Heaven''s Door', 30),
(null, 'Get in the Ring', 30),
(null, 'Shotgun Blues', 30),
(null, 'Breakdown', 30),
(null, 'Pretty Tied Up', 30),
(null, 'Locomotive', 30),
(null, 'So Fine', 30),
(null, 'Estranged', 30),
(null, 'You Could Be Mine', 30),
(null, 'Don''t Cry (Alt. Lyrics)', 30),
(null, 'My World', 30),
(null, 'Coma', 30),


(null, 'Rock and Roll Never Forgets', 31),
(null, 'Night Moves', 31),
(null, 'The Fire Down Below', 31),
(null, 'Sunburst', 31),
(null, 'Sunspot Baby', 31),
(null, 'Mainstreet', 31),
(null, 'Come to Papa', 31),
(null, 'Ship of Fools', 31),
(null, 'Mary Lou and the Cotton Dance', 31),
(null, 'Jody Girl', 31),
(null, 'Midnight Moves', 31),
(null, 'Detroit Rock', 31),
(null, 'Motor City', 31),
(null, 'Silver Bullet', 31),
(null, 'American Rock', 31),


(null, 'Hollywood Nights', 32),
(null, 'Still the Same', 32),
(null, 'Old Time Rock and Roll', 32),
(null, 'Till It Shines', 32),
(null, 'Feel Like a Number', 32),
(null, 'Ain''t Got No Money', 32),
(null, 'We''ve Got Tonight', 32),
(null, 'Brave Strangers', 32),
(null, 'The Famous Final Scene', 32),
(null, 'Stranger Blues', 32),
(null, 'Town Square', 32),
(null, 'Unknown Territory', 32),
(null, 'Foreign Land', 32),
(null, 'New Place', 32),
(null, 'Outsider', 32),


(null, 'The Horizontal Bop', 33),
(null, 'You''ll Accomp''ny Me', 33),
(null, 'Her Strut', 33),
(null, 'No Man''s Land', 33),
(null, 'Long Twin Silver Line', 33),
(null, 'Against the Wind', 33),
(null, 'Good for Me', 33),
(null, 'Betty Lou''s Gettin'' Out Tonight', 33),
(null, 'Fire Lake', 33),
(null, 'Shinin'' Brightly', 33),
(null, 'Wind Resistance', 33),
(null, 'Storm Fighter', 33),
(null, 'Weather Man', 33),
(null, 'Hurricane', 33),
(null, 'Tornado', 33),


(null, 'Battery', 34),
(null, 'Master of Puppets', 34),
(null, 'The Thing That Should Not Be', 34),
(null, 'Welcome Home (Sanitarium)', 34),
(null, 'Disposable Heroes', 34),
(null, 'Leper Messiah', 34),
(null, 'Orion', 34),
(null, 'Damage, Inc.', 34),
(null, 'Dyers Eve', 34),
(null, 'Blackened', 34),
(null, 'Harvester of Sorrow', 34),
(null, 'Eye of the Beholder', 34),
(null, 'One', 34),
(null, 'The Shortest Straw', 34),
(null, 'To Live Is to Die', 34),


(null, 'Blackened', 35),
(null, 'And Justice for All', 35),
(null, 'Eye of the Beholder', 35),
(null, 'One', 35),
(null, 'The Shortest Straw', 35),
(null, 'Harvester of Sorrow', 35),
(null, 'The Frayed Ends of Sanity', 35),
(null, 'To Live Is to Die', 35),
(null, 'Dyers Eve', 35),
(null, 'My Friend of Misery', 35),
(null, 'The Struggle Within', 35),
(null, 'Don''t Tread on Me', 35),
(null, 'Through the Never', 35),
(null, 'Nothing Else Matters', 35),
(null, 'Of Wolf and Man', 35),


(null, 'Enter Sandman', 36),
(null, 'Sad but True', 36),
(null, 'Holier Than Thou', 36),
(null, 'The Unforgiven', 36),
(null, 'Wherever I May Roam', 36),
(null, 'Don''t Tread on Me', 36),
(null, 'Through the Never', 36),
(null, 'Nothing Else Matters', 36),
(null, 'Of Wolf and Man', 36),
(null, 'The God That Failed', 36),
(null, 'My Friend of Misery', 36),
(null, 'The Struggle Within', 36),
(null, 'Stone Cold Crazy', 36),
(null, 'So What', 36),
(null, 'Killing Time', 36),


(null, 'Speak to Me', 37),
(null, 'Breathe', 37),
(null, 'On the Run', 37),
(null, 'Time', 37),
(null, 'The Great Gig in the Sky', 37),
(null, 'Money', 37),
(null, 'Us and Them', 37),
(null, 'Any Colour You Like', 37),
(null, 'Brain Damage', 37),
(null, 'Eclipse', 37),
(null, 'Dark Side', 37),
(null, 'Lunar Eclipse', 37),
(null, 'Moon Phase', 37),
(null, 'Cosmic Journey', 37),
(null, 'Space Oddity', 37),


(null, 'Shine On You Crazy Diamond (Parts I-V)', 38),
(null, 'Welcome to the Machine', 38),
(null, 'Have a Cigar', 38),
(null, 'Wish You Were Here', 38),
(null, 'Shine On You Crazy Diamond (Parts VI-IX)', 38),
(null, 'Burning Bridges', 38),
(null, 'Raving and Drooling', 38),
(null, 'Gotta Be Crazy', 38),
(null, 'Shine On', 38),
(null, 'Machine Dreams', 38),
(null, 'Cigar Smoke', 38),
(null, 'Missing You', 38),
(null, 'Absent Friends', 38),
(null, 'Diamond Dogs', 38),
(null, 'Crazy Diamond', 38),


(null, 'In the Flesh?', 39),
(null, 'The Thin Ice', 39),
(null, 'Another Brick in the Wall Part 1', 39),
(null, 'The Happiest Days of Our Lives', 39),
(null, 'Another Brick in the Wall Part 2', 39),
(null, 'Mother', 39),
(null, 'Goodbye Blue Sky', 39),
(null, 'Empty Spaces', 39),
(null, 'Young Lust', 39),
(null, 'One of My Turns', 39),
(null, 'Don''t Leave Me Now', 39),
(null, 'Another Brick in the Wall Part 3', 39),
(null, 'Goodbye Cruel World', 39),
(null, 'Hey You', 39),
(null, 'Is There Anybody Out There?', 39),


(null, 'There''s No Me Without You', 40),
(null, 'Don''t Take Your Love', 40),
(null, 'Hurt', 40),
(null, 'From Atlanta to Goodbye', 40),
(null, 'It''s Gonna Take a Lot of River', 40),
(null, 'The Way We Were', 40),
(null, 'One Life to Live', 40),
(null, 'Summertime in the City', 40),
(null, 'Love Is', 40),
(null, 'You Are My Heaven', 40),
(null, 'Soul Connection', 40),
(null, 'R&B Classic', 40),
(null, 'Smooth Soul', 40),
(null, 'Love Ballad', 40),
(null, 'Manhattan Nights', 40),


(null, 'That''s How Much I Love You', 41),
(null, 'Don''t Take Your Love Away', 41),
(null, 'It Feels So Good to Be Loved So Bad', 41),
(null, 'Hurt So Bad', 41),
(null, 'I Kinda Miss You', 41),
(null, 'The Picture Became Quite Clear', 41),
(null, 'Love Talk', 41),
(null, 'A Million to One', 41),
(null, 'Wonderful World of Love', 41),
(null, 'I''ll Never Find Another', 41),
(null, 'Deep Love', 41),
(null, 'Soul Serenade', 41),
(null, 'Romantic Evening', 41),
(null, 'Love Measure', 41),
(null, 'Heart Full', 41),


(null, 'Kiss and Say Goodbye', 42),
(null, 'Hurt', 42),
(null, 'Don''t Take Your Love', 42),
(null, 'We Never Danced to a Love Song', 42),
(null, 'There''s No Good in Goodbye', 42),
(null, 'Everybody Has a Dream', 42),
(null, 'You''d Better Believe It', 42),
(null, 'I''ll Never Find Another', 42),
(null, 'Love Is All We Need', 42),
(null, 'The Way We Were', 42),
(null, 'Manhattan Soul', 42),
(null, 'City Lights', 42),
(null, 'Urban Love', 42),
(null, 'Street Corner', 42),
(null, 'Doo Wop', 42),

(null, '742617000027', 43),
(null, '(sic)', 43),
(null, 'Eyeless', 43),
(null, 'Wait and Bleed', 43),
(null, 'Surfacing', 43),
(null, 'Spit It Out', 43),
(null, 'Tattered & Torn', 43),
(null, 'Me Inside', 43),
(null, 'Liberate', 43),
(null, 'Prosthetics', 43),
(null, 'No Life', 43),
(null, 'Diluted', 43),
(null, 'Only One', 43),
(null, 'Scissors', 43),
(null, 'Eeyore', 43),


(null, '(515)', 44),
(null, 'People = Shit', 44),
(null, 'Disasterpiece', 44),
(null, 'My Plague', 44),
(null, 'Everything Ends', 44),
(null, 'The Heretic Anthem', 44),
(null, 'Gently', 44),
(null, 'Left Behind', 44),
(null, 'The Shape', 44),
(null, 'I Am Hated', 44),
(null, 'Skin Ticket', 44),
(null, 'New Abortion', 44),
(null, 'Metabolic', 44),
(null, 'Iowa', 44),
(null, 'Maggot Brain', 44),


(null, 'Prelude 3.0', 45),
(null, 'The Blister Exists', 45),
(null, 'Three Nil', 45),
(null, 'Duality', 45),
(null, 'Opium of the People', 45),
(null, 'Circle', 45),
(null, 'Welcome', 45),
(null, 'Vermilion', 45),
(null, 'Pulse of the Maggots', 45),
(null, 'Before I Forget', 45),
(null, 'Vermilion Pt. 2', 45),
(null, 'The Nameless', 45),
(null, 'The Virus of Life', 45),
(null, 'Danger - Keep Away', 45),
(null, 'Scream', 45);
